### PR TITLE
Add a new QOL improvement to the user's workflow experience: Candence style zoom with RMB click and drag (addressing #264)

### PR DESCRIPTION
**Pull request by TheSUPERCD**
Added a new QOL improvement: Press down the RMB-button and drag the mouse to create a rectangle. Now releasing the RMB-button will allow zooming into the drawn rectangle. The context action menu that used to appear upon RMB-press-down action will now only appear if the user clicks the RMB-button without dragging the mouse.

This addition addresses feature request #264.

### CODE REVIEW

**Comment by TheSUPERCD** [comment]
Here is a simple demonstration of the workflow enhancement:

https://github.com/user-attachments/assets/08e8b410-9692-40c5-b7ce-79293ec12dcc

**Comment by StefanSchippers** [comment]
I have implemented the Right-Button-Drag to zoom an area and moved the context menu on Right Button Release.

If something stops working please report. Thank you.

**Comment by ananthchellappa** [comment]
That was really quick integration. Thank you Stefan. Verified latest version has the new feature.

Unrelated, when I go to Help > About, I get a window that gives the version and links for docs. If I click on local manual, I get File not found:

Firefox can’t find the file at /usr/local/share/doc/xschem/xschem_man/xschem_man.html. Minor, but if easy to fix..

**Comment by StefanSchippers** [comment]
that file should be in place if you do `make install` after compiling xschem.
I have fixed the unfound error if running xschem from the src/directory (where all references are from the source tree)

**Pull request closed without merging**
